#USE THE MODULES IN PYTHON 

# Math module

import math

print("Square root of 25:", math.sqrt(25))
print("Value of Pi:", math.pi)

# Random module
import random
print("Random number between 1 and 10:", random.randint(1, 10))

# Datetime module
from datetime import datetime
print("Current Date & Time:", datetime.now())

# OS module
import os
print("Current Working Directory:", os.getcwd())

# Sys module
import sys
print("Python Version:", sys.version)
